### ISSUE TITLE
Thanks for doing this!

### ISSUE THREAD

**Issue by bryanwweber** [comocheng/cantera-build#1]
This is a great idea! Can I suggest we move it (or perhaps fork it) into the Cantera org? This is something I've been trying to figure out how we can communicate better for a long time, and having a separate repo we can link to would be great without cluttering the Cantera/cantera repo.

cc/ @speth @ischoegl @decaluwe (I'm not sure if those will actually work)

**Comment by rwest** [comment]
Happy to move it, if there's consensus that's helpful.
Something like this could be be helpful for workshops etc.

**Comment by ischoegl** [comment]
Fwiw, the yaml is the same as the one I created for the website [here](https://cantera.org/compiling/installation-reqs.html#conda-requirements), with a couple of lines uncommented. If things are moved, the website should redirect to the repo.

**Comment by bryanwweber** [comment]
Just to clarify my thoughts here... I think it would be tremendously useful to make available "official" `environment.yml`, `conda-lock.yml`, `requirements.txt`, `Dockerfile`, etc. for _developers_ to set up environments to develop Cantera itself. I just went through trying to set up an environment myself and I always forget this or that dependency that I hardly use (especially for docs builds).

We (Cantera committers) have agreed that having all those files in the Cantera/cantera repo would be to much clutter, and I also think listing all of them on the website (other than as links). For some reason, I never thought of having a separate repo devoted to these things, so when this came across my feed this morning, I got very excited 😄 

@ischoegl Ah, thanks, I didn't realize you had created this `environment.yml` file and included it on the website. Yes, my intention is that we could link to a repo instead of including the files directly on the website.

**Comment by rwest** [comment]
Yes - I did nothing clever here - just followed your instructions (thank you for providing them!); I made this repo just for convenience for myself. But if having something like this is also convenient for others then we can share it more widely.

**Comment by ischoegl** [comment]
I'm overall :+1: with moving. I originally created the file out of convenience for my own builds, and put it on the website so others can use it also ...

**Comment by bryanwweber** [comment]
@ischoegl If you want to create a repo in the Cantera org with your file, that'd also be great. I'm not sure who has access to move/create repos in the Cantera org

**Comment by ischoegl** [comment]
@bryanwweber ... not sure how moving works, but I think a standard co-author statement in the commit message is perfectly adequate.

**Comment by rwest** [comment]
Should I archive this repo or something? Is it now redundant and leaving it discoverable is unhelpful?

**Comment by bryanwweber** [comment]
No I don't think you need to do anything, I was just cleaning out some old issues in my pile 😊
